# # hpa-demo.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: php-apache
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: php-apache
#   template:
#     metadata:
#       labels:
#         app: php-apache
#     spec:
#       containers:
#       - name: php-apache
#         image: k8s.gcr.io/hpa-example
#         ports:
#         - containerPort: 80
#         resources:
#           requests:
#             cpu: 200m
#           limits:
#             cpu: 500m
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: php-apache
# spec:
#   ports:
#   - port: 80
#   selector:
#     app: php-apache

# hpa-demo.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 80
  selector:
    app: nginx
