name: ad-service-ci

on:
  pull_request:
    branches: [main]
  push:
    paths:
      - '.github/workflows/ad.yaml'
      - 'src/ad/**'
  pull_request_target:
    branches: [main]
    paths:
      - '.github/workflows/ad.yaml'
      - 'src/ad/**'

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Give Gradle permission to execute
        run: chmod +x ./src/ad/gradlew
      
      - name: Run unit tests
        working-directory: ./src/ad
        run: ./gradlew test

  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: true  # 👈 Add this line to allow failure
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Give Gradle permission to execute
        run: chmod +x ./src/ad/gradlew

      - name: Run Google Java Format Check
        working-directory: ./src/ad
        run: ./gradlew verifyGoogleJavaFormat